# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- "*"

stages:
  - stage: test
    jobs:
      - job: 'validateandtest'
        pool:
          vmimage: windows-latest
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'ARM_Template_Service'
            subscriptionId: '445c11b8-59e8-495f-8cfd-83dd1ba1bc97'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'Try_resource'
            location: 'West Europe'
            templateLocation: 'Linked artifact'
            csmFile: '$(Build.SourcesDirectory)/ARM_Template/azuredeploy.json'
            csmParametersFile: '$(Build.SourcesDirectory)/ARM_Template/azuredeploy.parameters.json'
            deploymentMode: 'Validation'
        


            
            
    

          